import Head from 'next/head'
import '../styles/Main.css'
import Link from "next/link";
import Image from "next/image"

function MyApp({ Component, pageProps }) {
  return <div>
    <Head>
      <title>DJ Kecsa</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <nav className="nav">
      <div className="kecsa">
        <Image alt="logo" width="130px" height="30px" src="https://i.postimg.cc/W3p6qCkN/logo.png" />
      </div>

      <div className="links">
        <Link href="/">Kezdőlap</Link>
        <Link href="/About">Bemutatkozó</Link>
        <Link href="/Equipment">Felszerelés</Link>
        <Link href="/Contact">Kapcsolat</Link>
      </div>

      <div className="bid">
        <Link href="/Bidding">Árajánlat kérés</Link>
      </div>
    </nav>
    <Component {...pageProps} />
  </div>
}

export default MyApp
