import Head from 'next/head'
import '../styles/Main.css'
import Nav from '../components/Nav'

function MyApp({ Component, pageProps }) {
  return <div>
    <Head>
        <title>DJ Kecsa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Nav/>
    <Component {...pageProps} />
  </div>
}

export default MyApp
