import Head from 'next/head'
import '../styles/Main.css'
import Link from "next/link";
import Image from "next/image"
import { useState } from 'react';
import logo from '../public/images/logo.png'


function MyApp({ Component, pageProps }) {
  const [click, setClick] = useState(false);
  const handleClick = () => setClick(!click);
  const closeMenu = () => { setClick(false) };
  return (
    <div>
      <Head>
        <title>DJ Kecsa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous" />
      </Head>

      <nav className='nav'>
        <Link href="/" passHref onClick={closeMenu}>
          <div className="kecsa">
            <Image alt="logo" width="140px" height="30px" src={logo} />
          </div>
        </Link>

        <div className={click ? 'links active' : 'links'}>
          <Link href="/" passHref>
            <a onClick={closeMenu}>Kezdőlap</a>
          </Link>
          <Link href="/bemutatkozo" passHref>
            <a onClick={closeMenu}>Bemutatkozó</a>
          </Link>
          <Link href="/felszereles" passHref>
            <a onClick={closeMenu}>Felszerelés</a>
          </Link>
          <Link href="/kapcsolat" passHref>
            <a onClick={closeMenu}>Kapcsolat</a>
          </Link>
        </div>

        <div className="menu-icon" onClick={handleClick}>
          <i className={click ? 'fas fa-times' : 'fas fa-bars'} />
        </div>        

        <div className="bid">
          <Link href="/arajanlat">Árajánlat kérés</Link>
        </div>
      </nav>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
